# Generated by Django 5.0.1 on 2024-01-17 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Podologo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("costo", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora", models.DateTimeField()),
                (
                    "nombre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Coder.paciente",
                    ),
                ),
                (
                    "podologo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Coder.podologo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TratamientoParaCita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Coder.cita"
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coder.tratamiento",
                    ),
                ),
            ],
        ),
    ]
